name: Wheels

on:
  pull_request:
    paths:
      - '**'
  push:
    paths:
      - '**'

jobs:

  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - uses: pypa/cibuildwheel@v2.16
      env:
        CIBW_ARCHS_MACOS: auto universal2

#    - name: Upload wheels
#      uses: actions/upload-artifact@v3
#      with:
#        path: wheelhouse/*.whl


